[en]
  languageName = "English"
  languageCode = "en"
  weight = 1
  title = "Nathan's Blog"
  [en.params]
    tagline = "👋🏻 Hi, I’m Nathan, a UK-based technical professional focused on AI, Automation, Cloud Services and System Administration"