[en]
  label = "English"
  locale = "en"
  weight = 1
  title = "Nathan Darker"
  [en.params]
    tagline = "👋🏻 Hi, I’m Nathan, a UK-based technical professional working in DevOps environments, with a focus on cloud-native systems, Linux, Docker, and AI"
